spring:
  application:
    name: aolifu-mongo
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      username: root
      password: root
      database: db_student

server:
  port: 10004


