elasticjob:
  jobs:
    myJob:
      elasticJobClass: com.aolifu.elasticjob.lite.MyJob
      cron: 0/5 * * * * ?
      timeZone: GMT+08:00
      shardingTotalCount: 3
    myJob2:
      elasticJobClass: com.aolifu.elasticjob.lite.MyJob2
      cron: 0/5 * * * * ?
      timeZone: GMT+08:00
      shardingTotalCount: 3
    multipleTaskJob:
      elasticJobClass: com.aolifu.elasticjob.lite.MultipleTaskJob
      cron: 0/5 * * * * ?
      timeZone: GMT+08:00
      shardingTotalCount: 3
  regCenter:
    serverLists: localhost:2181
    namespace: elasticjob-lite-springboot
  tracing:
    type: RDB
    # echo "dump@myJob" | nc localhost 9888 > dump.txt
  dump:
    port: 9888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java?useUnicode=true&characterEncoding=UTF-8
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  port: 10002

