server:
  port: 10004

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  application:
    name: aolifu-dubbo-provider
  protocol:
    port: 20880

spring:
  application:
    name: aolifu-dubbo-provider