server:
  port: 8082

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  application:
    name: aolifu-dubbo-provider
  protocol:
    port: 20880
    name: dubbo

spring:
  application:
    name: aolifu-dubbo-provider