server:
  port: 9000

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    subscribe: true
  application:
    name: aolifu-dubbo-consumer
  scan:
    base-packages: com.aolifu.dubbo
  consumer:
    check: false

spring:
  application:
    name: aolifu-dubbo-consumer