server:
  port: 10009

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    subscribe: true
  application:
    name: aolifu-dubbo-consumer
  scan:
    base-packages: com.aolifu.dubbo
  consumer:
    check: false
  protocol:
    port: 20881

spring:
  application:
    name: aolifu-dubbo-consumer