spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/java?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: aolifu-mybatis
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      username: root
      password: root
      database: db_student

    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: hello_ca
      username: cassandra
      password: cassandra
      session-name: Test Cluster
      local-datacenter: datacenter1

server:
  port: 10001

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.aolifu.mybatis.entity

logging:
  level:
    com:
      aolifu:
        mapper: info

rocketmq:
  name-server: localhost:9876
  producer:
    group: default_producer_group
    tls-enable: true
    access-key: rocketmq2
    secret-key: 12345678

  consumer:
    access-key: rocketmq2
    tls-enable: true
    secret-key: 12345678

tls:
  client:
    trustCertPath: /Users/wangqiang/Downloads/software/github/rocketmq-all-4.9.4-bin-release/tls/ca.pem
